### ISSUE TITLE
Options will not save

### ISSUE THREAD

**Issue by chrisvio** [Kiuryy/Bookmark_Sidebar#1]
Great extension. I've been looking for something like this for a while. Options will not save on a Mac, though. It doesn't seem to work for any of the options. It always says Changes saved successfully. There are no error messages or anything. I'm using I'm using MacOS 10.12.3, Chrome version 57.0.2987.110 (64-bit) and Bookmark Sidebar v1.4.3.

I also noticed that the sidebar inherits the zoom level of the current tab.

**Comment by Kiuryy** [comment]
Thank you for your feedback. 
I checked it myself and can reproduce it sometimes, most times the settings are getting saved, which is somehow weird.
I pushed the newest changes I made to the settings page to master, there are some changes regarding storage savings included which seems to fix the issue.
Please let me know if the problem still exists after updating to 1.4.4.
The zoom level is indeed inherited from the page, this is because the sidebar is added to the pages html, I will look for a solution to fix this.

**Comment by Kiuryy** [comment]
Fixed the zoom level issue in 10dbc0b4b7cebd52c52c9e5c2312d3c5e77c13c6
