### ISSUE TITLE
Hide fallback info on new tab page

### ISSUE THREAD

**Issue by congjinyebaiya** [Kiuryy/Bookmark_Sidebar#103]
I hope that this part of the content selected from the box can be removed or just reminded when using it for the first time, instead of showing it every time when i open it. This will affect the beauty of the page
![image](https://user-images.githubusercontent.com/41639269/87852250-e3770f80-c932-11ea-9dbe-7342f70d6c06.png)

**Comment by Kiuryy** [comment]
I suppose you are opening a new tab, then click the extension icon, which brings up this page? 
The sidebar is only working on regular websites and in any cases, where Chrome is not loading the sidebar (e.g. on their new tab page, or the settings), this fallback page will be displayed. The intention behind this is, that you can override the new tab page and directly show the sidebar, instead of using this fallback mechanism.

You can hide this box by enabling the checkbox, which will override the default new tab page of Chrome and directly brings up this page when you open a new tab.

If you want to keep your default new tab page, but use the sidebar this way, you can hide this box using a custom CSS snippet, you can paste in the settings of the extension ("Appearance" > "General" > "Additional options").

```
div#fallbackInfo.active {
 display: none;
}
```

**Comment by congjinyebaiya** [comment]
wow it's awesome man, must be the best extension i've used. It's totally worth to purchase. Thanx for your contribution and reply
