### ISSUE TITLE
Keep sidebar visible when switching back to a tab that already had it open.

### ISSUE THREAD

**Issue by psultan** [Kiuryy/Bookmark_Sidebar#104]
The sidebar seems to disappear whenever I switch tabs and then switch back. 

Current Behavior:
- Open bookmark sidebar in tab1.
- Switch to tab2.
- Switch back to tab1.  The sidebar disappears.

Desired Behavior:
- Open bookmark sidebar in tab1.
- Switch to tab2.
- Switch back to tab1.  The sidebar is still visible

**Comment by Kiuryy** [comment]
Thank you for sharing your idea. Changing this behaviour for all users is probably not a good idea. This also does not seem to be a feature which is frequently requested, but I think it's a good idea to have an option to configure this.

Since this is a rather easy implementation, I already added it with d7e8566bafecd35ca979843a1cc737bd7f281f74 as an expert option. Maybe I will also add this option in the regular settings page, if I have data to see how many people are using this option.

With the next release of the extension this new option will be included.

**Comment by psultan** [comment]
Just tried this out today.  It works perfect.  Thanks.

**Comment by Kiuryy** [comment]
Glad to hear 👍
