### ISSUE TITLE
Annoying auto focus on bookmark search bar

### ISSUE THREAD

**Issue by mankinskin** [Kiuryy/Bookmark_Sidebar#108]
Hi,
whenever I open a new tab and start typing, the bookmark search bar catches the input focus, even though I hardly ever use it. The default input focus should be in the browser search bar. Would be great if this auto-focus behavior could be relaxed.

**Comment by Kiuryy** [comment]
Do you mean the focus of the search field of the new tab page, rather than the address bar of Chrome? There is an option to focus the address bar in the settings of the extension. If you navigate to "New Tab" in the left menu, you will find an option called "Focus address bar", which controls this. Please let me know if I got you wrong.

**Comment by mankinskin** [comment]
Ah thank you! That was what I was looking for but I didn't find it, because I didn't realize that this was related to new tabs.
