### ISSUE TITLE
Open from top rather than left or right

### ISSUE THREAD

**Issue by ortonomy** [Kiuryy/Bookmark_Sidebar#110]
Would love an option to for the bookmark bar to open from the top and have a horizontal list. I know this is close to the standard Chrome bookmar bar, but the standard bar is not auto hide-able / collapsible like this extension.

**Comment by Kiuryy** [comment]
Thanks for the suggestion. I haven't planned to implement a horizontal "sidebar" feature. This would require a completely different UI, as well as making the toggle options to click the edge of the screen not working properly, since aiming a small pixel area at the top of the browser content is rather difficult.
I suppose, this would fit into a separate extension, instead of extending the sidebar extension for such an feature.
