### ISSUE TITLE
Add Edge Native Newtab

### ISSUE THREAD

**Issue by hello-smile6** [Kiuryy/Bookmark_Sidebar#113]
If the new tab page in Edge is redirected to [https://ntp.www.office.com/antp/content?locale=en-US&dsp=1&sp=Bing](https://ntp.www.office.com/antp/content?locale=en-US&dsp=1&sp=Bing) which happens to be the HTTPS version of the newtab, the title is set to "New Tab", and the address bar is auto-focused, you could gain access to the new tab page without a fallback version. I did it myself.

**Comment by Kiuryy** [comment]
The URL you mentioned is redirecting Edge to a sort of New tab page, but there, the sidebar is also not working for me. This does not seem to resolve the problem with the sidebar not working on the default new tab page.

This page also is not looking like the new tab page, since there, you just have a search field, rather the Microsoft apps, weather, newsfeed, etc.

**Comment by hello-smile6** [comment]
Ugh. Could you design a workaround? I should have realized that.

**Comment by hello-smile6** [comment]
How could that be used? Maybe an embed and spoofed HTTP request?

**Comment by hello-smile6** [comment]
I mean, make the browser think it can be embedded.

**Comment by Kiuryy** [comment]
Unfortunately you cannot embed the new tab page as iframe or something similar. It's intended by Edge/Chrome, that extensions are not loading their content into that page. This got implemented on purpuse with Chrome v61 a few years ago.

**Comment by hello-smile6** [comment]
Ugh!

**Comment by hello-smile6** [comment]
Here's another version: https://ntp.msn.com/edge/ntp?locale=en-US&title=New%20tab&item=flights:prg-enterpriseblended-t,1s-ent-microsoft&dsp=1&sp=Bing&query=enterprise

**Comment by hello-smile6** [comment]
It doesn't work, either.

**Comment by hello-smile6** [comment]
What about this? I'm testing myself. https://ntp.msn.com/edge/ntp?locale=en-US&title=New%20tab&item=flights:prg-enterpriseblended-t,1s-ent-microsoft&dsp=0&sp=Bing&query=enterprise

**Comment by hello-smile6** [comment]
No. But it's still nice to have the ability to send a user to a new tab. Even a website could do that!

**Comment by hello-smile6** [comment]
Is this impossible?

**Comment by hello-smile6** [comment]
@Kiuryy What if the browser extension explicitly requests access to whatever website the new tab is set to? Then would it have access?

**Comment by Kiuryy** [comment]
This is not possible. If the browser handles a website (like the links you shared) as new tab page, no extensions are being loaded and you cannot bypass this, because this is intended behaviour.

This is the reason, I added my replacement new tab page, so if you need access to your bookmarks on a new tab, you can activate this page. Other than that there is no way of making this work.
