### ISSUE TITLE
Swapping Tabs Closes The Sidebar

### ISSUE THREAD

**Issue by hello-smile6** [Kiuryy/Bookmark_Sidebar#117]
I noticed that if you change tabs, the sidebar closes. Could the sidebar be applied to all active tabs (not to interfere with the Edge sleeping tabs functionality) and toggled universally?

- [ ] Determine API Needed

- [ ] Design Features As Optional

- [ ] Public Release

**Comment by Kiuryy** [comment]
There is an expert setting to deactivate that the sidebar closes when you change tabs. This flag is called `closeOnTabChange`. I didn't add this as regular option yet, since I want to evaluate whether this is really something many people are looking for.

Opening the sidebar on all tabs when you open it in one tab is not possible, since this would not be very good in terms of performance.

**Comment by hello-smile6** [comment]
Please enable it, @Kiuryy.

**Comment by Kiuryy** [comment]
You mean to open the sidebar on all tabs simultaneous? I cannot do that, since this is a resource demanding operation (think about a user with many tabs opened) and a feature, which doesn't seem to be logical to me. The purpose of the sidebar is to be opened, so the user clicks a bookmark there, which redirects the user to another website. If the user wants to go to another bookmarked page then, he just can open the sidebar again choosing the next destination.

Opening the sidebar on all tabs at the same time just adds additional resources and, if having many tabs opened, certainly result in a freezing browser.

**Comment by hello-smile6** [comment]
What about using the webpage-level user focus API to detect if a page is active and show it on whatever tab is open?

**Comment by hello-smile6** [comment]
> There is an expert setting to deactivate that the sidebar closes when you change tabs. This flag is called `closeOnTabChange`. I didn't add this as regular option yet, since I want to evaluate whether this is really something many people are looking for.
> 
> Opening the sidebar on all tabs when you open it in one tab is not possible, since this would not be very good in terms of performance.

I would love to use that functionality, @Kiuryy. However, I do not have a premium key or the money to get one. Could you give me a premium key using the https://gitter.im/ private message system?

**Comment by Kiuryy** [comment]
> What about using the webpage-level user focus API to detect if a page is active and show it on whatever tab is open?

This would be possible, I suppose, but still not making this feature more useful. I don't think opening the sidebar on a tab to then switch the tab and open a bookmark in the sidebar of another tab is a common use case. Therefore I don't think investing time into this is a good idea, taking in mind that the expert option already exists to not close the sidebar automatically when changing tabs
