### ISSUE TITLE
Submit Pull Request To Microsoft Edge Source GitHub Repository For Native Sidebars By Browser Extensions

### ISSUE THREAD

**Issue by hello-smile6** [Kiuryy/Bookmark_Sidebar#119]
# I realized that many of the problems the browser extension has could be fixed if Microsoft Edge let browser extensions create sidebars. Well, they _don't._
What if @Kiuryy submitted an issue to [the Microsoft Edge GitHub repository](https://github.com/MicrosoftEdge/MSEdge) suggesting such a feature? If that was done, Microsoft would probably like the suggestion, as it would benefit them and have affects in profits _and_ be easy for them to integrate since they already have the Bing Search in Sidebar UI, and the bookmark sidebar would be greatly improved and would be able to retract its request for access to page content. This should be considered.

- [ ] Submit Issue to Microsoft Edge repository

- [ ] Wait for Approval or Disapproval

- [ ] If approved and added to Microsoft Edge browser, integrate feature into Microsoft Edge version of sidebar

- [ ] Update permissions list if needed

**Comment by Kiuryy** [comment]
You cannot submit issues to the Edge repository, just pull requests. Such an API for having a permanent sidebar existed years ago in Chromium, but got dropped by Google. Opera has one at the moment, I'm aware of.

Having a sidebar API implemented in Edge does not mean, that my extension can be used as a permanent sidebar anyway. This would need a completely new implementation specifically for Edge. I haven't planned to develop such an extension, since this all is a spare time project.

**Comment by hello-smile6** [comment]
You could always try to contact them somehow to get them to consider that. They're trying to make their browser as good as possible and have a group of people doing that. THey might like the suggestion and do it, if you suggest it correctly.

**Comment by Kiuryy** [comment]
I don't see why you want me to do that, since you can contact them as well, introducing the idea and possible use cases. Edge might get a native bookmark sidebar in a future release, but I doubt they will implement a new API to let extensions create one, too.
