### ISSUE TITLE
Did Bookmark Sidebar change owners?

### ISSUE THREAD

**Issue by hello-smile6** [Kiuryy/Bookmark_Sidebar#122]
I'm worried and just removed it.

**Comment by Kiuryy** [comment]
No need to worry, there is no change of owners. I'm just moving the extension backend to a new more powerful server with the latest update of the extension. In addition, I used this opportunity to update the domain name as well to 1) allow a better transition from the old to the new server and 2) finally use a .com address, instead of only a .de address (the old domain name was not available as .com domain anymore).

**Comment by hello-smile6** [comment]
Okay. I was worried it was overtaken by malware. I'll reinstall it now.
