### ISSUE TITLE
HELP! LOL

### ISSUE THREAD

**Issue by Eyedea420** [Kiuryy/Bookmark_Sidebar#123]
HELP!  Anyone lol.  has anyone experienced the sidebar errantly jamming up into  the chrome homepage and know how to fix the bug/glitch, (I don't know the terminology.  It's my favorite extension (sad face)  And if the computer genius that made this created this majestic piece of programming reads this,  and can  send in The Wolf" and make this problem go away,  I will, for the first time in my life, stop being a mooch and buy premium lol.

**Comment by Kiuryy** [comment]
I'm not sure what you are referring to, but I try to give you some information:

Are you trying to open the sidebar on the new tab page of Chrome? As a privacy policy, the browser prohibits extensions from working on the default New Tab page. Bookmark Sidebar provides a similar but alternate New Tab page, replacing the default, where the sidebar can be used. You can find the according options in the settings of the extension.

If this is not the issue, I would be glad if you provide more details about the problem you are experiencing. For problems with the extension you can also use the feedback form in the settings of the extension, since there, some diagnostic data will also be sent with your feedback message making it easier for me to provide help and debug problems.
