### ISSUE TITLE
for help

### ISSUE THREAD

**Issue by Bequiet2014** [Kiuryy/Bookmark_Sidebar#124]
Browsing frequency records will be deleted from time to time

**Comment by Kiuryy** [comment]
I suppose this happens, because the browsing frequency records are not stored in the sync storage, but locally on your device. So reinstalling the extension or the browser will reset the counters to zero again.

The reason why this is not synced, is that the sync storage is limited in size (https://developer.chrome.com/docs/extensions/reference/storage/#property-sync).

If you experience this issue without a reinstall of the browser, OS or extension, please let me know, so I can investigate this further.

**Comment by Bequiet2014** [comment]
Hello, I didn't install it again. I'm using edge browser
