### ISSUE TITLE
Zoom regression

### ISSUE THREAD

**Issue by chrisvio** [Kiuryy/Bookmark_Sidebar#2]
The sidebar seems be inheriting the zoom level from the current tab again.

**Comment by Kiuryy** [comment]
Disabling the page zoom for certain elements is no longer supported in chrome and removed in version 59. Because of this I cannot ignore the page zoom for the sidebar anymore.
If you like further information you can read the entry from the chrome platform status (https://www.chromestatus.com/features/4997605029314560).
I don't see any other possibility to bypass the zoom level, because I don't even have information about the current zoom value and so I can hardly scale the sidebar according this value.

**Comment by MartinLichtblau** [comment]
@Kiuryy Should be possible even without dedicated function, see https://stackoverflow.com/questions/21093570/force-page-zoom-at-100-with-js

**Comment by Kiuryy** [comment]
With the solution of the StackOverflow answer, you can just change the size of the sidebar, but not detect the zoom level of the user, which is required to know how to set the zoom property of the sidebar.

There are some "hacks" to achieve this, but none of them seems to work on the current version of Chrome anymore... You can read more about here:
https://stackoverflow.com/questions/1713771/how-to-detect-page-zoom-level-in-all-modern-browsers#5078596

`text-size-adjust: none` was removed a few years ago already, which was the way I implemented it initially.

`visualViewport API` is not detecting page zoom on desktop, just the pinch zoom on mobile devices.

The other solutions, which calculate the inner and outer width fail with hdpi displays, when the user has two monitors or when the browser is in window mode. 

There isn't a reliable way of detecting the zoom level I'm aware of other than these.
