### ISSUE TITLE
Start searching for a bookmark only when user stops typing for n milliseconds

### ISSUE THREAD

**Issue by EdwardDiehl** [Kiuryy/Bookmark_Sidebar#41]
Currently when user types some search term in the search input then it starts searching immediately. If user has a lot of bookmarks then it becomes not very usable.

It would be good to not start searching immediately but only when user stops typing for n milliseconds.

**Comment by Kiuryy** [comment]
You are right, this isn't necessary at all and is causing the search to load very long, because the search is performed multiple times. I added a timeout of 500ms after the last keypress with 08e7403ef51b0f7071e4c20ab9e974e176068c87 before the search will be executed. This should result in a way better performance for a list of many bookmarks.
