### ISSUE TITLE
Bookmark is not visible in a folder for some period of time when i drag it from address bar

### ISSUE THREAD

**Issue by EdwardDiehl** [Kiuryy/Bookmark_Sidebar#48]
Steps to reproduce:
1. Delete a bookmarks from some folder.
2. Drag a bookmark from address bar to this folder.

The bookmark will appear in the folder in several minutes. Looks like the issue is connected with undo bookmark possibility from step 1.

**Comment by Kiuryy** [comment]
Thanks for reporting this issue, I could reproduce this behaviour and found the reason: 

If you delete an entry, you are able to undo this in the current tab, which will recreate the entry, but not triggering a reload (in the active tab, but in all others), because it basically just shows the deleted entry again. The problem was, that I didn't distinguished between entries which where created by the undo button and the ones created newly, so the reload was not performed in this case.

I fixed this bug in 14fbd94dede7375381348ed7550423d377a8aebb, creating entries will now properly reload the sidebar.
