### ISSUE TITLE
undefined at the end of the bookmark title

### ISSUE THREAD

**Issue by EdwardDiehl** [Kiuryy/Bookmark_Sidebar#53]
I tried to drag https://www.testdome.com/ site to my bookmarks and found out that the title of the bookmark has several `undefined` in a row at the end, it was like `TestDome | Programming Tests | Hire better programmersundefinedundefinedundefined`

**Comment by Kiuryy** [comment]
Thanks for mentioning, I can reproduce this issue, but still need to figure out why this is happening. Normally the title of the html document is taken as label for the bookmark, which obviously doesnt have the undefineds in it...

**Comment by EdwardDiehl** [comment]
I reproduced it with many other sites pages
for example
https://www.dailydrip.com/blog/ecto-vs-activerecord

**Comment by Kiuryy** [comment]
Thanks for the info. I found the cause of this issue and fixed it with b3eb9c8d8bb233a21b59c9f95895da34bb0bac6e.

The problem was the selector searching for the title-element in the document and use its content as label, when dragging the current url into the sidebar. The problem is, that some pages are using title-elements in svg-elements aswell, which produced the undefineds at the end of the label. I changed the selector to retrieve the page title properly and avoid conflicts with svg-elements.
