### ISSUE TITLE
New Tab - Focus on Chrome address bar instead of search box

### ISSUE THREAD

**Issue by jakub-astrahit** [Kiuryy/Bookmark_Sidebar#63]
When opening a new tab, I'd like to have my address bar focused automatically so I can start typing my URL directly and (often times) just select it from the suggestions in the dropdown (as suggested by Chrome automatically). Right now I can only type in the search box, which is not quite convenient. Would that be possible please?

**Comment by jakub-astrahit** [comment]
@Kiuryy Thanks for your fast response - I tried your workaround, but the problem is that it always selects the contents of the address bar - see the screenshot:

![address-bar](https://user-images.githubusercontent.com/19378338/45928599-694bee80-bf46-11e8-944a-a131572c2af0.png)

Is it possible to clear the address bar on focus please?

**Comment by Kiuryy** [comment]
Extensions cannot interact with the address bar and therefore cannot change what's being displayed there. The author of the extension, I mentioned, stated this is a few issues, e.g. here https://github.com/jimschubert/NewTab-Redirect/issues/141

Seems like another security restriction of Chrome.

**Comment by jakub-astrahit** [comment]
Ok, thanks. Keep up the good work!

**Comment by Kiuryy** [comment]
Of course I could just add the overwrite attribute in the manifest resulting in overwritting the new tab page. But that's something I don't want to do: If you install the extension, it should not overwrite the users new tab page, since this isn't logical for a sidebar extension at first. If the user later decides, he wants to use the new tab page of my extension, he should be able to enable it. 

Having an optional new tab replacement without messing the users previous new tab settings, is not possible in Chrome at the moment with the manifest approach. That's why I had to go another way, which has the downside with the address bar.
