### ISSUE TITLE
Select search results with Keyboard

### ISSUE THREAD

**Issue by MartinLichtblau** [Kiuryy/Bookmark_Sidebar#68]
Scenario: I search, get results and want to select the first one. 
1. Normally it's possible to use arrow keys. Should be a basic #feature
2. When using Tab, it jumps over the first entry. Seems like a #bug

P.S.: You've crafted a splendid piece of software.
P.S.: Ever thought about Omnibox integration?

**Comment by Kiuryy** [comment]
With 8ad306d48d0f16e66bebcce99e071098e63bdac0 I fixed the bug you mentioned: Using the `tab` key will now focus the first entry and not skip it. Thanks for mentioning :)

The `arrow` keys in the browser are used to scroll, which they can used for in the sidebar as well. I didn't wanted to override this default behaviour of the browser, so I took the `tab` key, which is meant to focus the next element of a website (or in case of the extension, the next bookmark).

To speed the search up, you can press `Enter` when the search result is only displaying one entry to open this bookmark without using the `tab` key first.

I haven't thought about an Omnibox integration yet, since Chrome is suggesting bookmarks already when typing in the Omnibox, I may give this a try and find out what I can do with the API to make it a useful addition.
