### ISSUE TITLE
Bookmark_Sidebar break Keepa extension

### ISSUE THREAD

**Issue by bewusiq** [Kiuryy/Bookmark_Sidebar#70]
I am using Chrome 72 with latest version of the extensions Bookmark Sidebar and Keepa.

When you load amazon.com and look for products we have iframe from the Keepa extension in the product page. When the boomark sidebar extension is active and the mouse hoover is in this iframe the mouse scrolling is sluggish and slow. If I disable the Bookmark sidebar extension the scrolling is working perfectly with the iframe from the Keepa extension, when I mouse hoover it.

**Comment by Kiuryy** [comment]
It's hard to tell what is causing the browser to freeze, since I don't know what Keepa is loading and how it works technically. I tested the mentioned issue myself and couldn' reproduce this issue on my system. I'm not certain about what I should fix or change at the sidebar extension, because there are many possible reasons for an slow responding Chrome.
What you can do, is adding a blacklist rule in the settings of the extension to prevent the sidebar from being loaded on the Amazon pages.

**Comment by bewusiq** [comment]
I was able to reproduce the issue and without the Bookmark Sidebar extension, so is something to do with the Keepa extension and Chrome 72. I am closing this.
