### ISSUE TITLE
it is not working today

### ISSUE THREAD

**Issue by waiaan** [Kiuryy/Bookmark_Sidebar#76]
here is the error:

Uncaught (in promise) RangeError: Invalid language tag: zh_cn
    at new Collator (<anonymous>)
    at e.I18nHelper.getLocaleSortCollator (extension.js:2)
    at e.UtilityHelper.sortEntries (extension.js:2)
    at e.ListHelper.addBookmarkDir (extension.js:2)
    at extension.js:2

**Comment by markwhitey** [comment]
me too

**Comment by bruce-ann** [comment]
same issue

**Comment by whatthetruth** [comment]
> me too
> same issue

Use the first version of 1.16.5:https://github.com/Kiuryy/Bookmark_Sidebar/releases/download/1.16.5/bookmark_sidebar_1.16.5.zip
The latest verion “1.16.5 Rev 12019/09/08” in Chrome store has problem and don't use it/

**Comment by yoyomasky** [comment]
me too

**Comment by shumouryou** [comment]
me too

**Comment by wuyiya** [comment]
mee Too

**Comment by wuyiya** [comment]
me too

**Comment by Kiuryy** [comment]
With the latest update I uploaded yesterday, I improved the language detection, which, apparently is breaking the extension for a significant amount of users. 

I already found the problem and hotfixed it. It may need a few hours until the fix will be approved by Google and then automatically installed on your system. The version with the fix for this issue is "1.16.5 rev3". I'm very sorry for this inconvenience and I hope everything is fine in a few hours.

**Comment by shenhuaxin** [comment]
me too

**Comment by huanglong6828** [comment]
me to

**Comment by litttlefisher** [comment]
me too

**Comment by killsting** [comment]
me too

**Comment by Kiuryy** [comment]
The bugfix is now live and is being distributed over the Chrome Webstore. The update should be installed automatically, but you can force the update process on `chrome://extensions/`.

I commited the according fix with 8a0c16babb6da65fdad5c68ad519df6b4ebf2cfc
