### ISSUE TITLE
New tab - Ability to search history

### ISSUE THREAD

**Issue by uyldrm** [Kiuryy/Bookmark_Sidebar#79]
When I move to a new tab, the cursor is automatically in the search box.
There are shortcuts that I have not bookmarked but frequently access without clicking on the address bar.
It would be great to access history from the search box.

**Comment by Kiuryy** [comment]
That's something I can probably add, since there is a history API. 

I will have a look at how Chrome is natively displaying the history in the omnibox and try to adapt this for the search box of the new tab page as well.

**Comment by Kiuryy** [comment]
I added the history entries to the search suggestions with 3e1e9b81c55782d769376f17b4c96d693506e651. This needs additional Chrome permissions, since the history is not accessable without the authorization of the user. This makes this feature only available for new users. To get the history suggestions when already using the extension, you need to disable the new tab page in the settings of the extension, saving this and then enabling it again. You then should be asked for the new history permission.

In order to make the suggestions more usable, for bookmark and history suggestions the url is now also displayed (in small) below the title (8c7fe63f7b6971362999a7b476ebedf2142b7ba6). On top, there are now more entries visible in the list (29e8918a11fe658102627354c78cfc9174287ead).

**Comment by uyldrm** [comment]
@Kiuryy When are you planning to release it or how could I access to this version?

**Comment by Kiuryy** [comment]
I'm currently testing the new features and will very likely upload it to the webstore the next week. It will need a couple of days to roll out for all users.

If you don't want to wait, you can load the extension from the the sources. You can read how to do that here: https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/.  The folder to select is the `src/` directory. Please note, that with this attempt, you will not receive updates via the webstore. It isn't meant for regular use, but for testing and playing with new features :)
