### ISSUE TITLE
Tab Groups

### ISSUE THREAD

**Issue by uyldrm** [Kiuryy/Bookmark_Sidebar#80]
As a user, I would like to save multiple tabs as a tab group so that I can open them in a new browser and continue working on them.

More details:
When working on a certain task (especially gsuite users that work on multiple documents), the user might open several chrome tabs and work referencing multiple of them. In the case, the user has to switch to another task, the currently open tabs become redundant but necessary to keep when he/she comes back. Please see as the following extension as a sample: https://chrome.google.com/webstore/detail/tab-group/gjgjkhbmehogehkdnoooeihkipifimme

PS: Thank you for being responsive the extension is great!!!

**Comment by Kiuryy** [comment]
Having tab groups would require sort of a different view in the sidebar (a list with saved groups) and a way of saving them (a dialog). But I don't think this is fitting into the extension, since this is more of a session management feature, rather than fitting into the Chrome bookmarking system. Besides, this is a very extensive feature for a rather small use case.

Since there is already at least one extension doing what you want, I don't think reinventing this for the bookmark sidebar extension is something I want to focus on.

**Comment by uyldrm** [comment]
Hi @Kiuryy,
I would feel the same way as the "new tab" functionality. However, I see these functionalities fall into "How might I help my users manage their short and long term bookmarks as well as quick start a new tab or window?" area. 
Not sure about the technical solution but it might as easy as creating a new tab on the sidebar that will switch between "Bookmarks Bar" and "Tab Groups". All the other functionality could stay the same such as drag and drop addition, etc. The user would add a folder manually and add tabs manually.
Again, I do respect your decision but I think this a useful enhancement.

**Comment by Kiuryy** [comment]
I only added the new tab functionality, because many users want to access the bookmarks from a new tab and Google removed the previously working possibility to load content into their new tab page.

The problem I have with the tab group idea is, that this is very complex and goes a bit too far from the original idea of the sidebar. I think this rather fits into a separate extension, since it covers a different use case.
