### ISSUE TITLE
Not refreshing bookmarks downloaded by Chrome sync

### ISSUE THREAD

**Issue by fermmm** [Kiuryy/Bookmark_Sidebar#82]
When the Chrome sync feature downloads bookmarks added from another computer the new bookmarks are not displayed in the bookmarks list of bookmarks sidebar but are present when going to settings button > bookmarks
A workaround to force bookmarks sidebar to refresh the bookmarks is by clicking on the "show hidden entries button."

**Comment by Kiuryy** [comment]
You are right, the bookmarks which were added by the sync mechanism aren't immediately visible in the sidebar, since the content is being cached. 
I added a "Reload sidebar" button in the same menu you mentioned, which is exactly for this purpose (reloading the sidebar to display the newly added bookmarks). I'm currently also investigating how to invalidate the cache for some cases, so that using this button isn't necessary anymore.
