### ISSUE TITLE
New Search Engines in New Tab

### ISSUE THREAD

**Issue by smaragdus** [Kiuryy/Bookmark_Sidebar#85]
You may consider adding a couple of search engines to the list in new tab page:

- [DuckDuckGo](https://duckduckgo.com/)
- [Qwant](https://www.qwant.com/)

as the search engines currently available cannot be a choice for those users who care for some (at least hypothetical) privacy. Of course this is not of great importance as the users can easily add their own user defined search engine yet this would be a tiny nice addition to the overall very pleasing extension.

**Comment by Kiuryy** [comment]
The search engines for mentioned doesn't seem to be commonly used and therefore I don't think putting them prominent in the list of the popular engines is something we should do.

The idea of the selection "custom" is actually, that users can use these niche search engines on the new tab page, but don't make the list too complicated with too much search engine entries.

**Comment by smaragdus** [comment]
@Kiuryy 

> The search engines for mentioned doesn't seem to be commonly used and therefore I don't think putting them prominent in the list of the popular engines is something we should do.

According to [this page](http://www.ebizmba.com/articles/search-engines) for example [DuckDuckGo](https://duckduckgo.com/) is more popular than [Yandex](https://yandex.com/) (as of January 2020).

> The idea of the selection "custom" is actually, that users can use these niche search engines on the new tab page, but don't make the list too complicated with too much search engine entries.

I do not think that [DuckDuckGo](https://duckduckgo.com/) is actually a niche search engine (you may have a look at [this article](https://www.ghacks.net/2020/01/09/duckduckgo-is-the-clear-winner-of-googles-first-android-search-provider-auction/) for example), I also think that open source developers might contribute a little by promoting privacy services as alternatives to services well-known as privacy disasters in their projects. Anyway, I am closing this issue.

**Comment by Kiuryy** [comment]
Just my two cents about the motivations: I put Yandex in favour of DuckDuckGo onto this list, since Yandex has a market share of 65% in Russia and is in global comparison a more popular search engine [1]. DuckDuckGo hasn't much users in a specific country (and global), making it a less popular choice.

I don't think pushing certain search engines just because of personal preferences is something we should do (be it an open-source project or not). The extension is used worldwide and other countries have different preferences (like Baidu is a big thing in China and DuckDuckGo is even blocked there [2]). With the list of predefined search engines, I tried to reflect that worldwide usage (and resort the entries based on user language)... there is no personal hatred from my side for DuckDuckGo.

[1] https://www.reliablesoft.net/top-10-search-engines-in-the-world/
[2] https://www.comparitech.com/privacy-security-tools/blockedinchina/duckduckgo/
