### ISSUE TITLE
Suggestion: Close all directories with one click

### ISSUE THREAD

**Issue by zhangchenglin** [Kiuryy/Bookmark_Sidebar#86]
First of all, you are great, he is easy to use, very convenient, and free to set combinations.
There is no suitable advice for you at the moment.
I wish you happy every day.

Show only current directory

Is it possible to add a shortcut function to close all tags with one click when it is not enabled?
Such as space or X.

**Comment by Kiuryy** [comment]
You can close all opened directories by clicking the menu icon in the header of the sidebar and then click on the according entry in the contextmenu. 
This feature is rarely used and in general something you don't click very often. Therefore I don't think adding an additional shortcut for this feature is needed at all. If you are using this very often, I think the option "Remember" in the settings of the extension ("Sidebar" > "General") might be interesting for you, because there, you can set the sidebar to not remember the opened directories when navigating to other pages and reopening the sidebar.

**Comment by zhangchenglin** [comment]
Text via Google Translate


I already have this button, that's enough.
There he is.
I have changed my scheme, I only have one directory expanded and the rest are closed automatically.
Because my directory sometimes has many levels, it is easy to get lost when going back. If that button can appear in a higher level when I need it, I will be happy to click on him. For example, next to the search button.
I just recommend it personally, mainly to let you know that your plugin is great. Great. Great.
