### ISSUE TITLE
may it disable google font?

### ISSUE THREAD

**Issue by zhangyc310** [Kiuryy/Bookmark_Sidebar#87]
3days ago, I install bookmark sidebar , It's beatiful and useful,I like it.
I found that , it load many google font from fonts.gstatic.com,
I try and found that  bookmark sidebar loads them.

I'm a programer with js and jquery .
It take me some truble,
the google font is make it more beautiful, 
but ,may some way to disable load google font . It's really takes me truble .
May give an swith to enable or disable load google fonts.
Thanks !

**Comment by Kiuryy** [comment]
The default font for the extension is automatically chosen based on the user language. For example Chinese/Japanese will use Noto and western languages Roboto. Since these fonts are very large, in fact more than 10 times larger than the actual source code, I didn't pack them in the extension, but load them from Google fonts. You can also read about this in the [privacy policy](https://extensions.blockbyte.de/privacy/bs)

If you don't like to have the Google fonts, you can choose another font in the settings of the extension ("Appearance" > "General") and pick a locally installed typeface.
