### ISSUE TITLE
Incompatibility with Chromium Wheel Smooth Scroller

### ISSUE THREAD

**Issue by ubreta** [Kiuryy/Bookmark_Sidebar#88]
I have latest version of Bookmark Sidebar and the extension Chromium Wheel Smooth Scroller, which you can find at https://chrome.google.com/webstore/detail/chromium-wheel-smooth-scr/khpcanbeojalbkpgpmjpdkjnkfcgfkhb?hl=en

I am opening this issue because there is bug between this 2 extensions.

1-Both extensions are with the default settings.
2-Make sure there are more than 50 bookmarks links, so they can be displayed in the Bookmark Sidebar.
3-Open any page, where we have scrolling indicator, just example https://www.google.com/search?q=chrome
4-Try to scrool the bookmarks with the mouse wheel, which are in the Bookmark Sidebar.
5-The scroll in the Bookmark Sidebar is not working.

That's pitty because both extensions separetly are going a great job.

**Comment by Kiuryy** [comment]
I just tested the steps, you provided and installed Chromium Wheel Smooth Scroller without changing configuration. For me, I can scroll on the google search result page, as well as the sidebar, if the smooth scroller is activated (I tried toggling it off and on, too, with the same result). It doesn't result in a conflict, other than this smooth scroller kills the mousepad scroll functionality for me and scrolling is only possible using a mouse wheel.

Even if there would be an incompatibility, I probably could not fix it from my side, since the sidebar is a simple iframe with a scrollable list in it and I haven't changed the default browser scroll behaviour at all. There is nothing I can do, to tell Chromium Wheel Smooth Scroller to work with the sidebar (or alternatively leave the sidebars default scroll behaviour). If you cannot scroll the sidebars content, you probably cannot scroll other embedded iframe containers on some websites, too, since there is no difference.

**Comment by ubreta** [comment]
I made a video for better explaining and understanding.
Please, check it at https://streamable.com/w040q

When I open the sidebar in my case the mouse scroll is working only on the page. It's not working is in the sidebar, where I am trying. The scroll in the sidebar is only working if I mouse click and hold ad drag, where is the scrolling indicator.

**Comment by Kiuryy** [comment]
Thanks for the video, but unfortunately that's exactly what I tried myself already. I may test it with another computer to check whether this is maybe happening there.

**Comment by ubreta** [comment]
I personally think that's more to do with the extension Chromium Wheel Smooth Scroller rather with the Bookmark Sidebar extension. I opened this issue to inform you in case you can do something from your end.

If you decide, please feel free to close this issue.

**Comment by ubreta** [comment]
The developer of the extension Chromium Wheel Smooth Scroller fixed this behavair. I could provide more details upon request.

There is no need this issue to be opened and I am closing it.
