### ISSUE TITLE
Cannot pass empty folder when traversing bookmarks with arrow keys

### ISSUE THREAD

**Issue by geo909** [Kiuryy/Bookmark_Sidebar#90]
Hi,

First, thanks a lot for your work.

I have the following issue.

**Reproduction steps**
1. Create an empty folder in the middle of your bookmarks
2. Open the sidebar with a keyboard shortcut 
3. Try to navigate from top to bottom by pressing the arrow key 

**Observed**
It is not possible to pass that empty bookmark folder

**Expected**
I would expect that by pressing the down arrow I would go to the next available bookmark or folder.
 
----

My bookmarks look as follows:
![2020-03-20-111856_388x669_scrot](https://user-images.githubusercontent.com/7989227/77151340-6039d000-6a9e-11ea-9a78-837fc11aff3e.png)

*EDIT: * While writing this and testing it, the arrow keys worked fine, passing the bookmark folder. Then restarting chromium, the issue reappeared. So, I'm not 100% of the context where this occurs, please check if you can reproduce it yourself.

Best regards

**Comment by Kiuryy** [comment]
Thanks for mentioning this. I just commited a fix for this (44dbb29314ce2b6d3528c9b148e009237cebb533). The problem occured, when the empty directory was considered "opened". The mechanism to determine which is the next/prev element in the list then failed, since there were no bookmarks in the directory. This shouldn't happen anymore :)

This fix will be included in the next update of the extension, which I have planned to upload to the webstore the next week after some more testing.

**Comment by geo909** [comment]
Hi, that was quick, thanks! Looking forward to the new version.

Cheers.
