### ISSUE TITLE
Feature Request: Bookmark Backup!

### ISSUE THREAD

**Issue by akhan4u** [Kiuryy/Bookmark_Sidebar#92]
Hi Phillip,

I am really liking your bookmark extension. Wouldn't it be great if you can add a bookmark backup feature also like saving the bookmarks at a specific interval on some drive or something?

**Comment by Kiuryy** [comment]
I haven't planned to implement something like this, because your bookmarks are already being backed up by Chrome when you are logged in with your Google account. 
You can also export/import a html file using the default bookmark manager manually, in case you don't want to use a Google account. 

Implementing a custom backup solution would need to work with all common cloud providers and therefore requires a huge amount of development and maintenance, so I don't think this is justifiable compared to the effort. This would rather fit into another stand-alone extension rather into this sidebar extension.
