### ISSUE TITLE
Bookmarks doesn't update in real-time

### ISSUE THREAD

**Issue by pingshunhuangalex** [Kiuryy/Bookmark_Sidebar#96]
After I added a new bookmark via the star icon in Chrome on address URL, the newly added bookmark is not visible in the sidebar, I'll need to refresh the page for it to show up...

**Comment by Kiuryy** [comment]
If you add a bookmark using the default manager (e.g. by clicking the star icon in the address bar), the sidebar refreshes to show the bookmark. This is happening, because Chrome is reporting the sidebar, that there was a change at the bookmarks, so the sidebar will clear its cache and reloads the list. 

The problem occurs when you change the folder of this newly created bookmark in the dialog. This change is not being reported by Chrome, so the extension doesn't know you moved the bookmark within this dialog to another folder. Therefore you need to manually trigger the update of the sidebar to have this bookmark displayed in the new folder in the sidebar. 

Unfortunately there is nothing I can do about this, since Chrome is simply not reporting this bookmark update to the extension.

**Comment by pingshunhuangalex** [comment]
Is it a limitation here because of the nature of this extension? I used neaterBookmark before which doesn't have this issue, but it's not creating a page overlay either. I don't have full context there either, just want to bring this up. Thanks.

**Comment by Kiuryy** [comment]
Yes, that's a limitation because of the way the sidebar is being loaded. Neater Bookmarks is loading the bookmarks when you click the extension icon in a popup window. The sidebar is different here, since it's already loaded and this dialog needs to tell the extension there was an update. Otherwise the sidebar doesn't know about and cannot refresh, which then displays outdated bookmarks.

**Comment by pingshunhuangalex** [comment]
I see. Makes sense. It's a bit of a shame but I can live with that. Feel free to close the ticket if there's no follow up action needed. Thanks for the explanations.

**Comment by hello-smile6** [comment]
What about setInterval refresh? I use setInterval on all my projects (sometimes with excessive timings) and it works well. Then, by setting an update every 33 ms, the extension woula appear to update instantly. (30 fps).
