### ISSUE TITLE
Allow an adjustable number of pinned bookmarks on New Tab

### ISSUE THREAD

**Issue by Bamba-Tom** [Kiuryy/Bookmark_Sidebar#99]
Currently this looks to be hardcoded at 8 (4x2) in the code. Could you make that adjustable as a user setting, or exposed in Expert Settings? 
Maybe within certain limits if rendering speed may be a concern (but unlikely with Elm ;-)
I have more pinned bookmarks that I would like to show and while I understand I could use the shortcuts feature, they are manually-made and with no icons.
Thanks.

**Comment by Kiuryy** [comment]
The current implementation is limited to the amount of 8 tiles. This is because there are checks to ensure all tiles are visible when resizing the browser window or when having configured a wide sidebar, which are currently hardcoded values.

I think I could change this approach to make it more general, so you can configure a custom grid size and the extension then handles the checks how much elements really fit on the current screen and reduce the amount of elements if needed dynamically.

**Comment by Bamba-Tom** [comment]
Thanks for considering this. As shown, for my use-case I have a bunch of space to work with. But understand that's not always the case.

![image (Small)_proc](https://user-images.githubusercontent.com/47292358/83934954-a9c9c980-a808-11ea-849e-061c13c6891b.jpg)
(and yes, BS is still very quick with that many bookmarks)

**Comment by Kiuryy** [comment]
I had a bit of time this weekend and changed the implementation of the grid. Now you can configure the amount of cols and rows. If the configured grid size won't fit on the screen, the extension will take care of removing some cols or rows.

f7c675ac46c4b7d40687ab2a56fab10faa59e7c1
e59a531b2cad9f9ac8455a9b6e24875e7cb184a8
c4468e8d26d98b47c23c8cf40659ea62a5bc9bd0

This still needs some testing and validation, but with the next update of the extension, I will include this updated configuration.

**Comment by Bamba-Tom** [comment]
That was quick! Thanks Philipp. Look forward to it. 

Craig.

**Comment by Kiuryy** [comment]
The update which includes the adjustable grid size on the new tab page is currently pending a review by Google and should be rolled out at some point next week.
